experiment_name: "BioLinkBert-large"
model_name: "michiyasunaga/BioLinkBERT-large"
training_data_path: "data_preprocessed/BioLinkBert-large/training.pkl"
validation_data_path: "data_preprocessed/BioLinkBert-large/validation.pkl"
hyperparameters:
  num_epochs: 32
  batch_size: 16
  learning_rate: 0.0001
  lr_scheduler_factor: 0.5
  lr_scheduler_threshold: 0.04
  freeze_epochs: 0
