experiment_name: "BioLinkBert-base_with_freezing"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/BioLinkBert-base/training.pkl"
validation_data_path: "data_preprocessed/BioLinkBert-base/validation.pkl"
hyperparameters:
  num_epochs: 32
  batch_size: 16
  learning_rate: 0.0001
  min_learning_rate: 0.0000001
  freeze_epochs: 24
