experiment_name: "BiomedBert-base-uncased-abstract-fulltext"
model_name: "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext"
training_data_path: "data_preprocessed/BiomedBert-base-uncased-abstract-fulltext/training.pkl"
validation_data_path: "data_preprocessed/BiomedBert-base-uncased-abstract-fulltext/validation.pkl"
hyperparameters:
  num_epochs: 32
  batch_size: 16
  learning_rate: 0.0001
  min_learning_rate: 0.0000001
  freeze_epochs: 24
