experiment_name: "ensemble_inference"
model_names:
  - "michiyasunaga/BioLinkBERT-large"
  - "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext"
  - "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract"
training_data_path: "data_preprocessed/ensemble_inference/training.pkl"
validation_data_path: "data_preprocessed/ensemble_inference/validation.pkl"
hyperparameters:
  num_epochs: 32
  batch_size: 16
  learning_rate: 0.0001
  lr_scheduler_factor: 0.5
  lr_scheduler_threshold: 0.03
  freeze_epochs: 0
