experiment_name: "BiomedElectra-large-freeze-24epochs"
model_name: "microsoft/BiomedNLP-BiomedELECTRA-large-uncased-abstract"
training_data_path: "data_preprocessed/BiomedElectra-large-freeze-24epochs/training.pkl"
validation_data_path: "data_preprocessed/BiomedElectra-large-freeze-24epochs/validation.pkl"
hyperparameters:
  num_epochs: 32
  batch_size: 16
  learning_rate: 0.0001
  lr_scheduler_factor: 0.5
  lr_scheduler_threshold: 0.04
  freeze_epochs: 24
