experiment_name: "BioM-ALBERT-xxlarge"
model_type: "huggingface"
model_name: "sultan/BioM-ALBERT-xxlarge"
dataset_qualities:
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: False
find_optimal_lr: False
weighted_training: False
hyperparameters:
  num_epochs: 40
  batch_size: 8
  lr_scheduler:
    learning_rate: 0.0001
    method: "custom"
    custom_schedule:
    - [0, 4, 1]
    - [5, 20, 2]
    step_size: 2
    gamma: 0.8
