experiment_name: "BioLinkBERT-base" # Descriptive name for this experiment run.
model_type: "huggingface" # or "bertlstmcrf" # Type of model to train.
model_name: "michiyasunaga/BioLinkBERT-base" # The Huggingface model identifier.
dataset_qualities: # Specify in this list which qualities of data should be included in the training dataset.
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: True # Boolean deciding if HTML should be removed from the data
weighted_training: False # Boolean for if the training data is weighted or not
dataset_weights: # Weights for weighted training. Has to correspond to the datasets the number and order of datasets in preprocessing/main.py
- 1.2
- 1.2
- 1.0
- 0.33
hyperparameters:
  num_epochs: 25 # Total number of full passes over the dataset.
  batch_size: 16 # Number of samples processed in one forward/backward pass.
  lr_scheduler:
    method: "cosine annealing"  # Name of the scheduling strategy for adjusting the learning rate.
    # Supported values:
    # - "cosine annealing"     → smooth decay using cosine curve.
    # - "reduce on plateau"    → reduce LR if validation metric stops improving.
    # - "custom"               → fully custom LR schedule.
    learning_rate: 0.0001 # Initial learning rate at the start of training.

    # ↓ Fields required by specific methods ↓

    # For 'cosine annealing':
    # num_epochs: Total number of training epochs for the scheduler to plan its decay.
    # min_learning_rate: The minimum learning rate the scheduer is allowed to reach.

    # For 'reduce on plateau':
    # factor: Factor by which the LR will be reduced.
    # patience: Number of epochs to wait before reducing LR.
    # threshold: Threshold for measuring new optimum, to ignore small improvements.

    # For 'custom':
    # LambdaLR for warmup and decay.
    # custom_schedule: Used for warmup with a list of 3-tuples (start_epoch, end_epoch, multiplier).
    # step_size: How many epochs before update the LR with a factor of gamma. Will update first time immediately after warmup. 
    # gamma: The factor to update the the LR with.
