experiment_name: "BERTLSTMCRF_more"
model_type: "bertlstmcrf"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/BERTLSTMCRF_more/training.pkl"
validation_data_path: "data_preprocessed/BERTLSTMCRF_more/validation.pkl"
weighted_training: False
hyperparameters:
  num_epochs: 30
  batch_size: 16
  freeze_epochs: 0
  lr_scheduler:
    method: "custom"
    learning_rate: 0.00004
    custom_schedule:
    - [0, 2, 1]
    - [3, 15, 2]
    step_size: 2
    gamma: 0.7