experiment_name: "BERTLSTMCRF"
model_type: "bertlstmcrf"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/BERTLSTMCRFetraining.pkl"
validation_data_path: "data_preprocessed/BERTLSTMCRF/validation.pkl"
weighted_training: False
hyperparameters:
  num_epochs: 20
  batch_size: 16
  freeze_epochs: 0
  lr_scheduler:
    method: "custom"
    learning_rate: 0.00002
    custom_schedule:
    - [0, 2, 1]
    - [3, 5, 2]
    step_size: 2
    gamma: 0.7