experiment_name: "BioLinkBERT-base-weighted"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/BioLinkBERT-base-weighted/training.pkl"
validation_data_path: "data_preprocessed/BioLinkBERT-base-weighted/validation.pkl"
hyperparameters:
  num_epochs: 12
  batch_size: 16
  learning_rate: 0.0001
  min_learning_rate: 0.0000001
  freeze_epochs: 0
