experiment_name: "BioLinkBERT-base"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/BioLinkBERT-base/training_with_html.pkl"
validation_data_path: "data_preprocessed/BioLinkBERT-base/validation_with_html.pkl"
hyperparameters:
  num_epochs: 25
  batch_size: 16
  learning_rate: 0.0001
  min_learning_rate: 0.0000001
  freeze_epochs: 0
