experiment_name: "BioLinkBert-large"
model_name: "michiyasunaga/BioLinkBERT-large"
training_data_path: "data_preprocessed/training.pkl"
validation_data_path: "data_preprocessed/validation.pkl"
hyperparameters:
  num_epochs: 3
  batch_size: 16
  learning_rate: 0.00002
