experiment_name: "BioLinkBERT-base"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/BioLinkBERT-base/training.pkl"
validation_data_path: "data_preprocessed/BioLinkBERT-base/validation.pkl"
weighted_training: True
dataset_weights:
- 1.0
- 1.0
- 1.0
- 0.33
hyperparameters:
  num_epochs: 20
  batch_size: 32
  freeze_epochs: 0
  lr_scheduler:
    method: "custom"
    learning_rate: 0.00002
    custom_schedule:
    - [0, 2, 1]
    - [3, 5, 2]
    step_size: 2
    gamma: 0.7