experiment_name: "BioLinkBERT-base"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/BioLinkBERT-base/training_with_html.pkl"
validation_data_path: "data_preprocessed/BioLinkBERT-base/validation_with_html.pkl"
weighted_training: False
hyperparameters:
  num_epochs: 20
  batch_size: 32
  freeze_epochs: 0
  lr_scheduler:
    method: "multistep"
    learning_rate: 0.0001
    milestones:
    - 5
    - 10
    - 15
    gamma: 0.1