experiment_name: "BioLinkBert-large-freeze-8-epochs-out-of-16-epochs"
model_name: "michiyasunaga/BioLinkBERT-large"
training_data_path: "data_preprocessed/training_concatenated.pkl"
validation_data_path: "data_preprocessed/validation_concatenated.pkl"
hyperparameters:
  num_epochs: 16
  batch_size: 16
  learning_rate: 0.00002
  freeze_epochs: 8
