experiment_name: "BioMed-RoBERTa-base"
model_name: "allenai/biomed_roberta_base"
training_data_path: "data_preprocessed/BioMed-RoBERTa-base/training.pkl"
validation_data_path: "data_preprocessed/BioMed-RoBERTa-base/validation.pkl"
hyperparameters:
  num_epochs: 25
  batch_size: 16
  learning_rate: 0.0001
  min_learning_rate: 0.0000001
  freeze_epochs: 0
