experiment_name: "BiomedBERT-base-uncased-abstract-fulltext"
model_name: "microsoft/BiomedBERT-base-uncased-abstract-fulltext"
training_data_path: "data_preprocessed/training.pkl"
validation_data_path: "data_preprocessed/validation.pkl"
hyperparameters:
  num_epochs: 12
  batch_size: 16
  learning_rate: 0.00002
  freeze_model: true
