experiment_name: "Bob2"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/Bob2/training.pkl"
validation_data_path: "data_preprocessed/Bob2/validation.pkl"
hyperparameters:
  num_epochs: 32
  batch_size: 16
  learning_rate: 0.00002
  lr_scheduler_factor: 0.5
  freeze_epochs: 0
