experiment_name: "LR_finder_test"
model_type: "huggingface"
model_name: "michiyasunaga/BioLinkBERT-base"
dataset_qualities:
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: True
weighted_training: True
dataset_weights:
- 1.25
- 1.25
- 1.25
- 0.75
find_optimal_lr: False
hyperparameters:
  num_epochs: 10
  batch_size: 16
  lr_scheduler:
    learning_rate: 0.001
    method: "one cycle"
    max_learning_rate: 0.001
    pct_start: 0.2
    div_factor: 20
    final_div_factor: 10000
