experiment_name: "BioLinkBERT-base"
model_type: "re"
subtask: "2.6.2"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/BioLinkBERT-base/training.pkl"
validation_data_path: "data_preprocessed/BioLinkBERT-base/validation.pkl"
weighted_training: False
dataset_qualities:
- "platinum"
- "gold"
remove_html: True
hyperparameters:
  num_epochs: 10
  batch_size: 16
  freeze_epochs: 0
  lr_scheduler:
    method: "custom"
    learning_rate: 0.00002
    custom_schedule:
    - [0, 2, 1]
    - [3, 12, 4]
    step_size: 2
    gamma: 0.8
