experiment_name: "biobert_ncbi_disease_ner"
model_type: "huggingface"
model_name: "ugaray96/biobert_ncbi_disease_ner"
dataset_qualities:
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: False
find_optimal_lr: False
weighted_training: True
dataset_weights:
- 1.25
- 1.25
- 1
- 0.75
hyperparameters:
  num_epochs: 30
  batch_size: 16
  lr_scheduler:
    learning_rate: 0.00002
    method: "custom"
    custom_schedule:
    - [0, 2, 1]
    - [3, 12, 3]
    step_size: 2
    gamma: 0.8