experiment_name: "BioLinkBERT-large"
model_type: "huggingface"
model_name: "michiyasunaga/BioLinkBERT-large"
dataset_qualities:
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: False
find_optimal_lr: False
weighted_training: False
hyperparameters:
  num_epochs: 23
  batch_size: 16
  lr_scheduler:
    learning_rate: 0.00002
    method: "custom"
    custom_schedule:
    - [0, 2, 1]
    - [3, 12, 4]
    step_size: 2
    gamma: 0.8
