experiment_name: "BioLinkBERT-base"
model_type: "huggingface"
model_name: "michiyasunaga/BioLinkBERT-base"
training_data_path: "data_preprocessed/BioLinkBERT-base/training.pkl"
validation_data_path: "data_preprocessed/BioLinkBERT-base/validation.pkl"
weighted_training: False
hyperparameters:
  num_epochs: 25
  batch_size: 16
  freeze_epochs: 0
  lr_scheduler:
    method: "custom"
    learning_rate: 0.00004
    custom_schedule:
    - [0, 2, 1]
    - [3, 10, 2]
    step_size: 2
    gamma: 0.7
