experiment_name: "BioM-ALBERT-xxlarge-PMC"
model_type: "huggingface"
model_name: "sultan/BioM-ALBERT-xxlarge-PMC"
training_data_path: "data_preprocessed/BioM-ALBERT-xxlarge-PMC/training.pkl"
validation_data_path: "data_preprocessed/BioM-ALBERT-xxlarge-PMC/validation.pkl"
weighted_training: False
hyperparameters:
  num_epochs: 50
  batch_size: 8
  freeze_epochs: 0
  lr_scheduler:
    method: "custom"
    learning_rate: 0.00004
    custom_schedule:
    - [0, 2, 1]
    - [3, 20, 2]
    step_size: 2
    gamma: 0.7
