experiment_name: "BiomedBERT-base-uncased-abstract"
model_type: "huggingface"
model_name: "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract"
dataset_qualities:
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: False
find_optimal_lr: True
remove_html: False
weighted_training: False
hyperparameters:
  num_epochs: 25
  batch_size: 16
  lr_scheduler:
    learning_rate: 0.00002
    method: "custom"
    custom_schedule:
    - [0, 2, 1]
    - [3, 9, 4]
    step_size: 2
    gamma: 0.8
