experiment_name: "BioM-ALBERT-xxlarge"
model_type: "huggingface"
model_name: "sultan/BioM-ALBERT-xxlarge"
dataset_qualities:
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: False
find_optimal_lr: True
weighted_training: False
hyperparameters:
  num_epochs: 50
  batch_size: 8
  freeze_epochs: 0
  lr_scheduler:
    method: "custom"
    learning_rate: 0.00004
    custom_schedule:
    - [0, 2, 1]
    - [3, 20, 2]
    step_size: 2
    gamma: 0.7
