experiment_name: "BiomedBERT-large-uncased-abstract"
model_name: "microsoft/BiomedBERT-large-uncased-abstract"
training_data_path: "data_preprocessed/BiomedBERT-large-uncased-abstract/training.pkl"
validation_data_path: "data_preprocessed/BiomedBERT-large-uncased-abstract/validation.pkl"
weighted_training: False
hyperparameters:
  num_epochs: 30
  batch_size: 16
  freeze_epochs: 0
  lr_scheduler:
    method: "custom"
    learning_rate: 0.00004
    custom_schedule:
    - [0, 2, 1]
    - [3, 15, 2]
    step_size: 2
    gamma: 0.7
