experiment_name: "BERTLSTMCRF"
model_type: "bertlstmcrf"
model_name: "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext"
dataset_qualities:
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: False
weighted_training: True
dataset_weights:
- 1.25
- 1.25
- 1
- 0.75
find_optimal_lr: False
hyperparameters:
  num_epochs: 30
  batch_size: 16
  freeze_epochs: 4
  lr_scheduler:
    learning_rate: 0.00002
    method: "custom"
    custom_schedule:
    - [0, 0, 1]
    - [1, 1, 2]
    - [2, 2, 3]
    - [3, 12, 4]
    step_size: 2
    gamma: 0.8
