experiment_name: "BioLinkBERT-base"
model_type: "huggingface"
model_name: "michiyasunaga/BioLinkBERT-base"
dataset_qualities:
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: False
weighted_training: True
dataset_weights:
- 1.5
- 1.5
- 1.5
- 0.75
hyperparameters:
  num_epochs: 30
  batch_size: 16
  lr_scheduler:
    learning_rate: 0.00002
    method: "custom"
    custom_schedule:
    - [0, 2, 1]
    - [3, 12, 4]
    step_size: 2
    gamma: 0.8