experiment_name: "BioLinkBERT-base"
model_type: "huggingface"
model_name: "michiyasunaga/BioLinkBERT-base"
dataset_qualities:
- "platinum"
- "gold"
- "silver"
- "bronze"
remove_html: True
weighted_training: True
dataset_weights:
- 1.25
- 1.25
- 1.25
- 0.5
hyperparameters:
  num_epochs: 30
  batch_size: 16
  freeze_epochs: 0
  lr_scheduler:
    method: "custom"
    learning_rate: 0.00004
    custom_schedule:
    - [0, 2, 1]
    - [3, 10, 2]
    step_size: 2
    gamma: 0.7
